# Generated by Django 4.1.1 on 2023-04-03 21:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0005_category_parent'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='category',
            options={'ordering': ['parent__id', 'position'], 'verbose_name': 'دسته بندی', 'verbose_name_plural': 'عنوان دسته بندی ها'},
        ),
    ]
